jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: '2020'
      port: 5432
      dbname: jaffle_shop
      schema: dbt_cngue
      threads: 4